project:
  type: website

website:
  title: "Análise de Dados Sociais"
  navbar:
    left:
      - text: "Início"
        href: index.qmd
      - text: "Sobre"
        href: about.qmd
  sidebar:
    style: "floating"
    search: true
    collapse-level: 2
    contents:
      - index.qmd
      - intro-dplyr.qmd
  page-navigation: true
  

format:
  html:
    theme:
      light: [cosmo, pers_layout.scss]
      dark: [darkly, pers_layout.scss]
    toc: true
    toc-location: right
    toc-title: "Conteúdo"
    toc-depth: 3
    smooth-scroll: true
    include-after-body: tracker.html
